### ISSUE TITLE
fatal error: 'SeExpression.h' file  not found

### ISSUE THREAD

**Issue by sabotage3d** [wdas/partio#62] opened 2016-08-28 20:01 UTC
Hi I am building Partio without python bindings but I am getting  this error:

`Scanning dependencies of target partioSe
[ 42%] Building CXX object src/lib/CMakeFiles/partioSe.dir/PartioSe.o
In file included from /DEV/libs/partio/src/lib/PartioSe.cpp:35:
/DEV/libs/partio/src/lib/PartioSe.h:36:10: fatal error: 'SeExpression.h' file
      not found
# include <SeExpression.h>

```
     ^
```

1 error generated.`

**Comment by ahmedelsheikh** [comment] 2016-10-24 20:30
same issue:

/partio-master/src/lib/PartioSe.h:36:10: fatal error: 
      'SeExpression.h' file not found
#include <SeExpression.h>
         ^
1 error generated.
make[2]: *** [src/lib/CMakeFiles/partioSe.dir/PartioSe.o] Error 1
make[1]: *** [src/lib/CMakeFiles/partioSe.dir/all] Error 2
make: *** [all] Error 2

**Comment by davvid** [comment] 2016-10-26 23:47
You need wdas/SeExpr to build PartioSe.  We should probably document this better in the README along with the necessary build flags / environment variables.

**Comment by brucedjones** [comment] 2017-08-24 14:05
This is still a problem with the current master branch of SeExpr built and installed. This is because evrything in SeExpr got refactored from SeExpr to Expr, including filenames. Unfortunately making this change in PartioSe.h and PartioSe.cpp hasn't fixed the problem and results in a bunch of errors stemming from the included SeExpr header files.

**Comment by davvid** [comment] 2017-08-26 03:42
Specifically, use SeExpr `v2.11` for now.  SeExpr was designed so that v2 and the newer LLVM-based v3+ could co-exist.  There's a PR where someone started porting to v3, but it's incomplete so it won't be merged for now, but it probably does build.  The classes involved there are aux stuff that are not part of partio's core, so you don't really need it.

**Comment by brucedjones** [comment] 2017-08-26 10:20
Thanks, I will take a look at v2.11.

In the long run wouldn't it be better to remove this dependency? SeExpr has many more dependencies that don't seem to be required in partio. This isn't a problem on Linux so much but on Windows it makes the build much more of a chore.

**Comment by dracwyrm** [comment] 2017-08-26 11:54
I use this patch to cut out a lot of depends on SeExpr:
https://github.com/dracwyrm/gentoo-ebuilds/blob/master/media-libs/SeExpr/files/SeExpr-2.11-build-fixes.patch
It basically stops the gui from building, which isn't needed if you are just using the SeExpr libraries in Partio. This makes the depends simple (RDEPEND are runtime and the others are compile only):
```
RDEPEND="sys-devel/llvm:=
	media-libs/libpng:0=
	virtual/opengl"

DEPEND="${RDEPEND}
	doc? ( app-doc/doxygen )
	sys-devel/bison
	sys-devel/flex
	virtual/pkgconfig"
```
The patch also builds SeExpr with C++11 ABI. :) You can probably remove the part where it adds findpackage(PyQt4). That was my attempt to fix Qt detection, but it didn't work, which is why I disabled the gui part to begin with.

**Comment by davvid** [comment] 2017-08-26 17:55
Yes, the aux PartioSe class was an experiment and not something we really need.  I'd just as quickly merge a PR that removes the SeExpr dependency.

**Comment by dracwyrm** [comment] 2017-08-26 18:19
@davvid You mean completely remove _all_ PartioSe and the depends to SeExpr?

**Comment by davvid** [comment] 2017-08-26 19:12
I'm probably being a little heavy-handed by suggesting a removal.  I'll document it for now.  I also switched to `unique_ptr` instead of `auto_ptr` since we support c++11, and I'd happily take any other steps towards better c++11 citizenship (nullptr, etc).

**Closed** 2017-08-26 19:13 UTC

**Comment by davvid** [comment] 2017-08-26 19:23
For completeness, the updated build instructions are documented here: https://github.com/wdas/partio#super-impatient-building-guide

What would be a nice addition (in case someone wants to trim dependencies) would be a `Makefile` and `cmake` option to enable/disable the SeExpr support.  That could be forwarded to the code as a `#define` that can be used to disable including those files in the swig interface files.

**Comment by davvid** [comment] 2017-08-26 19:57
I just made it optional now too, so this should build fine by default now unless you've opted into the SeExpr support.

**Comment by brucedjones** [comment] 2017-08-28 17:21
Hey thanks the new option is great!
